kind: Deployment
apiVersion: apps/v1
metadata:
  name: chimnguyen
spec:
  replicas: 2
  selector: # tells the controller which pods to watch/belong to
    matchLabels:
      app: chimnguyen
  template:
    metadata:
      labels:
        app: chimnguyen
    spec:
      containers:
        - name: chimnguyen
          image: chimnguyen/kubernestest-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
